In [2]:
import numpy as np

In [3]:
X1=np.random.randint(10, size=6)
print("X1=",X1, sep='')

X1=[3 8 8 1 4 6]


In [4]:
X2=np.random.randint(10, size=(3, 4))
print("X2=%s" % X2)

X2=[[1 6 7 7]
 [0 9 3 6]
 [5 3 2 6]]


In [5]:
X3=np.random.randint(10, size=(3,4,5))
print(f"X3={X3}")

X3=[[[9 5 7 7 1]
  [4 9 3 7 2]
  [5 5 3 7 4]
  [0 3 9 2 9]]

 [[3 2 0 0 4]
  [7 8 7 8 5]
  [2 8 9 2 4]
  [3 7 6 0 1]]

 [[9 4 7 5 9]
  [9 2 8 8 2]
  [7 4 1 6 1]
  [3 0 4 5 9]]]


In [6]:
X1[0]=10

In [7]:
X1

array([10,  8,  8,  1,  4,  6])

In [8]:
X1[-1]

6

In [9]:
X2[0,0]=14

In [10]:
X2

array([[14,  6,  7,  7],
       [ 0,  9,  3,  6],
       [ 5,  3,  2,  6]])

In [11]:
X2[1,-1]

6

In [12]:
nums=np.arange(10)
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1, 10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
x=np.array([1, 2, 3])
x

array([1, 2, 3])

In [15]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [16]:
x.shape

(3,)

In [17]:
xa=x[np.newaxis,:]
display(xa)
xa.shape

array([[1, 2, 3]])

(1, 3)

In [19]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [22]:
nums[:5:2]

array([0, 2, 4])

In [23]:
nums[3:7]

array([3, 4, 5, 6])

In [24]:
nums[::2]

array([0, 2, 4, 6, 8])

In [30]:
nums[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
nums[::-2]

array([9, 7, 5, 3, 1])

In [32]:
nums1=nums.copy()
nums1[4:8]=20
nums1

array([ 0,  1,  2,  3, 20, 20, 20, 20,  8,  9])

In [33]:
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
X2

array([[14,  6,  7,  7],
       [ 0,  9,  3,  6],
       [ 5,  3,  2,  6]])

In [36]:
X2[:2,:3]

array([[14,  6,  7],
       [ 0,  9,  3]])

In [37]:
X2[:3, ::2]

array([[14,  7],
       [ 0,  3],
       [ 5,  2]])

In [39]:
X2[:3, ::-2]

array([[7, 6],
       [6, 9],
       [6, 3]])

In [42]:
X2[::-1,::-1]

array([[ 6,  2,  3,  5],
       [ 6,  3,  9,  0],
       [ 7,  7,  6, 14]])

In [43]:
X2[::-1]

array([[ 5,  3,  2,  6],
       [ 0,  9,  3,  6],
       [14,  6,  7,  7]])

In [45]:
X2[:,::-1]

array([[ 7,  7,  6, 14],
       [ 6,  3,  9,  0],
       [ 6,  2,  3,  5]])

In [47]:
X2[0,:]

array([14,  6,  7,  7])

In [48]:
X2[:,0]

array([14,  0,  5])

In [3]:
xb=np.arange(12).reshape((2,2,3))
xb

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [54]:
xb[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
xb[1][::-1,:]

array([[ 9, 10, 11],
       [ 6,  7,  8]])

In [60]:
xb[1,::-1]

array([[ 9, 10, 11],
       [ 6,  7,  8]])

In [62]:
xc=np.random.randint(30, size=(3,3))
xc

array([[ 2, 15, 19],
       [29,  8,  9],
       [ 7, 10, 11]])

In [63]:
xc[:2,1:]

array([[15, 19],
       [ 8,  9]])

In [64]:
xc[:2,1:].shape

(2, 2)

In [65]:
xc[:,:2]

array([[ 2, 15],
       [29,  8],
       [ 7, 10]])

In [66]:
xc[1,:2]

array([29,  8])

In [67]:
xc.shape

(3, 3)

In [72]:
xc[1:2,:2]

array([[29,  8]])

In [74]:
xd=np.arange(27).reshape((3,3,3))
xd

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
xd[:,:,2][0]

array([2, 5, 8])

In [81]:
xe=np.random.randint(30, size=(2,2))
xf=np.random.randint(30, size=(2,2))
display(xe)
display(xf)

array([[ 2, 27],
       [25, 27]])

array([[22, 10],
       [ 3, 26]])

In [83]:
xg=np.concatenate([xe,xf])
xg

array([[ 2, 27],
       [25, 27],
       [22, 10],
       [ 3, 26]])

In [85]:
xd[...,0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [88]:
xd[...,1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [87]:
xh=np.random.randint(100, size=(3,3))
xi=np.random.randint(100, size=(3,3))
xj=np.concatenate([xh,xi])
xj

array([[31, 79, 53],
       [78, 68, 88],
       [28, 98, 40],
       [80, 92, 29],
       [76, 16, 50],
       [42, 23, 53]])

In [89]:
xj

array([[31, 79, 53],
       [78, 68, 88],
       [28, 98, 40],
       [80, 92, 29],
       [76, 16, 50],
       [42, 23, 53]])