In [1]:
num1=3
num2=2
sum=num1+num2
print(sum)

5


In [2]:
sum

5

## heading

In [3]:
import numpy as np
np.ndarray([1,2])

array([[ 2.63764426e+282, -4.65076620e+083]])

In [6]:
import sys
sys.version

'3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]'

In [13]:
import platform
platform.system(), platform.version()

('Windows', '10.0.19044')

In [15]:
x=np.array([1,2,3,4,5,6])

In [18]:
print("My array is {0}".format([1,2,3,4]))
print(f"My array is {x}")

My array is [1, 2, 3, 4]
My array is [1 2 3 4 5 6]


In [16]:
x.shape

(6,)

In [17]:
x.size

6

In [22]:
x=np.array([[[1,2],[3,4],[5,6]],[7,8]],dtype=object)
print(x)

[list([[1, 2], [3, 4], [5, 6]]) list([7, 8])]


In [29]:
np.zeros((10,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [50]:
np.arange(1,20+1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
[i for i in range(1,21)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [55]:
l=[]
for i in range(1,21):
    l.append(i)
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [36]:
np.identity(7,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [40]:
import random
random.randint(0,20)

17

In [46]:
np.random.randn(3,4)

array([[ 0.67756492, -0.34797981, -1.19265259, -1.47223272],
       [ 1.81873346,  0.8887376 , -1.1283733 , -0.14056652],
       [-1.4609618 ,  0.62736044, -2.28108661,  1.68923348]])

In [47]:
np.random.normal(3,4)

10.134245277084172

In [56]:
a=int(input("Enter number a "))
b=int(input("Enter number b "))
print(f"sum={a+b}\naverage={(a+b)/2}")

Enter number a 30
Enter number b 50
sum=80
average=40.0


In [61]:
def grade(score):
    for i in score:
        if i >0 and i <=40:
            print("FAIL")
        elif i > 40 and i <= 50:
            print("D")
        elif i >50 and i <=60:
            print("C")
        elif i>60 and i<=70:
            print("B")
        elif i>70 and i < 100:
            print("A")
        else:
            print("Not valid")
        
if __name__=='__main__':
    grades=(input("Enter score: "),input("Enter score: "),input("Enter score: "))
    grade([int(i) for i in grades])

Enter score: 70
Enter score: 69
Enter score: 80
B
B
A
